### ISSUE TITLE
Release artifacts to bintray

### ISSUE THREAD

**Issue by ahonor** [rerun/rerun#198]
Modify build setup to publish artifacts to the bintray repos. There are three repositories created under the 'rerun' organization, one for each artifact type:
- bin: https://bintray.com/rerun/rerun-bin
- rpm: https://bintray.com/rerun/rerun-rpm
- deb: https://bintray.com/rerun/rerun-deb

**Comment by stagrlee** [comment]
Lots of wrestling with automake, but it works finally.
