### ISSUE TITLE
RERUN_VERSION isn't unified across execution, setup, and packaging

### ISSUE THREAD

**Issue by eedwardsav** [rerun/rerun#249]
The RERUN_VERSION is set/grabbed in two places:

configure.ac -- used for dist packaging
```
AC_INIT([rerun], [1.3.8], [rerun-discuss@googlegroups.com]
```

setup.sh -- used to grab version and populate RERUN_VERSION, but doesn't actually change package name made
```
RERUN_VERSION=$(grep ^RERUN_VERSION rerun  | cut -d= -f2)
```

rerun
```
RERUN_VERSION=1.3.8
```

As you can see, this means the version needs to be changed in two places.

I suggest we change this to have them all source the version from the same file for consistency, and allows a CI system to easily modify version, as needed.

I will open a PR

**Comment by ahonor** [comment]
+1

**Comment by stagrlee** [comment]
Duplication is Evil...  +1
