### ISSUE TITLE
not working "readonly variable"

### ISSUE THREAD

**Issue by grasys-yano** [rerun/rerun#265]
Commits on Jan 19, 2018 ,or 
Commits on Nov 11, 2017 
./rerun is not working.(#841b1ddb6dca26a0bd015be987169e6df7b5b5bb)

here is my execute result
```
git clone --depth 1 https://github.com/rerun/rerun.git /opt/rerun

#install mustache
rerun mustache: mustache

#Error Messages
#/opt/rerun/rerun: line 1042: COMMAND_SHELL: readonly variable
```

In this case, workaround is using past version.
```
git reset --hard a7f848c1a6ecdffba7abfd35654a076a94f71071
```

**Comment by ahonor** [comment]
Hi @grasys-yano, did the mustache command use sudo?

**Comment by grasys-yano** [comment]
>did the mustache command use sudo?
Thank you for your reply.

This script did not use sudo.
But my usecase is always execute in su user (root user).

Here is mustache/script
It execute git only.
```
#!/bin/env bash

mustache_repo=https://github.com/tests-always-included/mo.git
mustache_deploy=/opt/mo

echo "setup: mustache"
if [ ! -d $mustache_deploy ]; then
  git clone --depth 1 $mustache_repo $mustache_deploy
else
  cd $mustache_deploy && git pull origin master
fi
```
